language: r
sudo: required
warnings_are_errors: true
env:
  global:
    - NOT_CRAN=true
before_install: 
  - echo "options(repos = c(CRAN='http://cloud.r-project.org/'))" > ~/.Rprofile
apt_packages:
 - r-cran-rgdal
 - r-cran-ncdf4
r_packages:
 - caret
 - corrplot
 - dismo
 - fields
 - geoR
 - ggplot2
 - gridExtra
 - gstat
 - pgirmess
 - raster
 - rasterVis
 - rgdal
 - rgeos
 - sp
